# Generated by Django 3.2.8 on 2021-12-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video', models.FileField(blank=True, upload_to='original')),
                ('skeleton_video', models.FileField(blank=True, upload_to='skeleton')),
            ],
        ),
    ]
