# Generated by Django 3.2.8 on 2021-12-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20211219_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcheck',
            name='additional_feedback',
            field=models.TextField(null=True),
        ),
    ]
